export const states = [
    { key: "AL", text: "Alabama", value: "Alabama" },
    { key: "AK", text: "Alaska", value: "Alaska" },
    { key: "AR", text: "Arkansas", value: "Arkansas" },
    { key: "AZ", text: "Arizona", value: "Arizona" },
    { key: "CA", text: "California", value: "California" },
    { key: "CO", text: "Colorado", value: "Colorado" },
    { key: "CT", text: "Connecticut", value: "Connecticut" },
    { key: "DC", text: "D.C.", value: "D.C." },
    { key: "DE", text: "Delaware", value: "Delaware" },
    { key: "FL", text: "Florida", value: "Florida" },
    { key: "GA", text: "Georgia", value: "Georgia" },
    { key: "HI", text: "Hawaii", value: "Hawaii" },
    { key: "IA", text: "Iowa", value: "Iowa" },
    { key: "ID", text: "Idaho", value: "Idaho" },
    { key: "IL", text: "Illinois", value: "Illinois" },
    { key: "IN", text: "Indiana", value: "Indiana" },
    { key: "KS", text: "Kansas", value: "Kansas" },
    { key: "KY", text: "Kentucky", value: "Kentucky" },
    { key: "LA", text: "Louisiana", value: "Louisiana" },
    { key: "MA", text: "Massachusetts", value: "Massachusetts" },
    { key: "MD", text: "Maryland", value: "Maryland" },
    { key: "ME", text: "Maine", value: "Maine" },
    { key: "MI", text: "Michigan", value: "Michigan" },
    { key: "MN", text: "Minnesota", value: "Minnesota" },
    { key: "MO", text: "Missouri", value: "Missouri" },
    { key: "MS", text: "Mississippi", value: "Mississippi" },
    { key: "MT", text: "Montana", value: "Montana" },
    { key: "NC", text: "North Carolina", value: "North Carolina" },
    { key: "ND", text: "North Dakota", value: "North Dakota" },
    { key: "NE", text: "Nebraska", value: "Nebraska" },
    { key: "NH", text: "New Hampshire", value: "New Hampshire" },
    { key: "NJ", text: "New Jersey", value: "New Jersey" },
    { key: "NM", text: "New Mexico", value: "New Mexico" },
    { key: "NV", text: "Nevada", value: "Nevada" },
    { key: "NY", text: "New York", value: "New York" },
    { key: "OK", text: "Oklahoma", value: "Oklahoma" },
    { key: "OH", text: "Ohio", value: "Ohio" },
    { key: "OR", text: "Oregon", value: "Oregon" },
    { key: "PA", text: "Pennsylvania", value: "Pennsylvania" },
    { key: "RI", text: "Rhode Island", value: "Rhode Island" },
    { key: "SC", text: "South Carolina", value: "South Carolina" },
    { key: "SD", text: "South Dakota", value: "South Dakota" },
    { key: "TN", text: "Tennessee", value: "Tennessee" },
    { key: "TX", text: "Texas", value: "Texas" },
    { key: "UT", text: "Utah", value: "Utah" },
    { key: "VA", text: "Virginia", value: "Virginia" },
    { key: "VT", text: "Vermont", value: "Vermont" },
    { key: "WA", text: "Washington", value: "Washington" },
    { key: "WI", text: "Wisconsin", value: "Wisconsin" },
    { key: "WV", text: "West Virginia", value: "West Virginia" },
    { key: "WY", text: "Wyoming", value: "Wyoming" }
];